# Generated by Django 5.2.4 on 2025-07-30 15:50

import subject_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='professor',
            field=models.CharField(default='Mr. Cahan', validators=[subject_app.validators.validate_professor_name]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(unique=True, validators=[subject_app.validators.validate_subject_format]),
        ),
    ]
